### ISSUE TITLE
Make Profile Detail Page

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/react-client-mui#24]

**Comment by keyxcode** [comment]
I just uploaded an early version of this @danielzeljko 
Currently I'm only using mock data, and you can find the page at /account/user
Check it out when you have time and lmk if you have any comments.

**Comment by danielzeljko** [comment]
Hi @keyxcode, thanks for being patient! I had some time to look at it and it looks great. The stats section is also a nice touch. We might need to replace the longest streak section with something else as streaks have been removed and I'm not sure if they'll be back. Maybe we can add post count, prompt count, or contribution ranking as well. 

Some minor changes are needed:
- [ ] Make the sidebar sticky so that when we scroll on large devices it will stay in place
- [ ] Change the positioning of the elements on mobile devices (it currently takes up too much vertical spacing)
- [ ] Change the URL endpoint to `/users/<some username>` (after moving from mockdata)
- [ ] Remove the `longest streak` stat

![image](https://github.com/LangCorrect/react-client-mui/assets/115326106/494978fb-6369-4165-8162-44afb156efcc)
![image](https://github.com/LangCorrect/react-client-mui/assets/115326106/e31109a3-fe3a-4605-b548-182bef31b23e)

**Comment by keyxcode** [comment]
Thanks for the feedback @danielzeljko !
Regarding point #2 about the mobile layout: I could bring it to where you wanted, but then it wouldn't look good on super narrow devices such as the Galaxy Fold. The MUI breakpoints are also not very good for these types of devices - they basically group everything with width under 600px in the xs category.
Would you say that we:
- Ignore these super narrow devices for now.
- Adjust the MUI theme and create a new breakpoint.
- Something else ... ?

**Comment by keyxcode** [comment]
Regarding the stats page, do you think it would be cool/ possible to have a line chart of the contributions? It's basically the same idea as the contribution graph of the current site but I think the current one looks a bit too GitHub-y for most people.
I'm thinking something like this: https://i.redd.it/rym4zupg9w881.jpg
Another thing I quite like from Duolingo is their achievements: https://duolingo.fandom.com/wiki/Achievements What are your thoughts on this?
