### ISSUE TITLE
Add a layout setting to toggle Right to Left (RTL) mode

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/react-client-mui#48]
![image](https://github.com/LangCorrect/react-client-mui/assets/115326106/5988ba7e-01e7-4f1e-8a4d-19a92527474c)

I'm thinking with RTL being another layout setting essentially, we can replace the `dark mode` icon with an MUI settings icon, and when clicked it will open up a Popover where we can toggle different settings.

Popover: https://mui.com/material-ui/react-popover/
Icon: https://mui.com/material-ui/material-icons/?query=settingfs&selected=Settings
Switch: https://mui.com/material-ui/react-switch/
MUI docs for RTL: https://mui.com/material-ui/guides/right-to-left/

**Comment by kelvinsekx** [comment]
Hey @danielzeljko,
Realized you are the project maintainer, and I would love to contribute to this.
How do I pick this issue? I mean I should start from good first issue 😂.

Also, you might need to update the description because what I am supposed to do, isn't super clear yet!

**Comment by kelvinsekx** [comment]
I just sent my IPv4 address and Github username to the support mail few minutes ago.

**Comment by danielzeljko** [comment]
@kelvinsekx

Thanks for offering to help out again! Access has been granted and the details are in the response email.

I'll update the description now.

**Comment by danielzeljko** [comment]
@kelvinsekx 

The description has been updated. Please let me know if you have any questions.

**Comment by kelvinsekx** [comment]
A. Here is what you want me to do?
+ replace dark mode icon with a settings icon
+ when the settings icon is clicked, a popover with the following contents as children
         + RTL + switch for RTL
         + Dark Mode Icon + switch for dark mode toggle
 
 B. My questions are:
 1. what should be used as the label for dark mode toggle as it switches on and off? It should be the same dark mode icon as it is presently? 
 Presently on the LangCorrect site, if I toggle dark and light mode with the icon, the icon doesn't change.
 2. This experience should be the same for RTL? That upon switch on and off, the label remains RTL.
 
![react-mui-nav](https://github.com/LangCorrect/react-client-mui/assets/51183064/925b5884-b887-4114-9a7e-77f13f2622ac)

**Comment by danielzeljko** [comment]
Those are some great questions.

A - Looks good!

B - I think it would be best, for now at least, to just remove the dark mode icon and replace it with a string label that says `Dark Mode`. I really want to make sure that the layout is consistent as that is an area where I struggle honestly. Let's keep the labels the same even if the switch is toggled on and off.

**Comment by kelvinsekx** [comment]
Great. Thanks for the thoughtful response.
It's dark my time here (10:32pm). So I would work on it tomorrow morning. Have a good night.

**Comment by kelvinsekx** [comment]
State of development
- working on the code

**Comment by kelvinsekx** [comment]
State of dev
- code complete, waiting for merge
