### ISSUE TITLE
Hide the correct button when viewing own post

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/react-client-mui#53]
![Image](https://github.com/LangCorrect/react-client-mui/assets/115326106/8bf39c43-09e1-4677-bc33-bda7ef05f2d8)

This button can be found in the `Post` component

**Comment by Kayvin59** [comment]
Hi @danielzeljko can you assign me this issue ?

**Comment by danielzeljko** [comment]
Hi @Kayvin59,

I'd love to! Thanks for deciding to contribute!

I have assigned the issue to you. You'll be able to find this button in the `Post `component. Please don't forget to read the ReadMe as it has important information on getting set up and accessing the staging environment.

**Comment by danielzeljko** [comment]
Hi @Kayvin59, I'm just checking in. How's everything going?

**Comment by Kayvin59** [comment]
Hi Daniel, I have some issues when trying to create an account to access the Post page. It returns a 404 error. I have been following your guidelines by modifying VITE_API_BASE_URL with the url you provide me. Any ideas ?


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : Daniel Zeljko ***@***.***>
Envoyé : jeudi 15 juin 2023 22:44
À : LangCorrect/react-client-mui ***@***.***>
Cc : Kayvin ***@***.***>; Mention ***@***.***>
Objet : Re: [LangCorrect/react-client-mui] Hide the correct button when viewing own post (Issue #53)


Hi @Kayvin59<https://github.com/Kayvin59>, I'm just checking in. How's everything going?

**Comment by danielzeljko** [comment]
Hi @Kayvin59, I sent you a reply via email a little while back. Have you received it? Can you let me know if you are still interested to work on this issue? If not I will take over. Thanks!
